hafproject/hafapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('home', views.home, name='home'),
    path('pricing', views.pricing, name='pricing'),
    path('booksession', views.booksession, name='booksession'),
    path('faqs', views.faqs, name='faqs'),
    path('about', views.about, name='about'),
    path('order', views.order, name='order'),
    path('thankyou', views.thankyou, name='thankyou'),
]

hafproject/hafproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hafapp.urls')) # Add this line to include the hafapp urls.py file
]

hafproject/hafapp/models.py
from django.db import models

class OrderData(models.Model):
   firstname = models.CharField(max_length=200)
   cases = models.CharField(max_length=200)

   def __str__(self):
       return f'{self.firstname} : {self.cases}'

hafproject/hafapp/forms.py
from django import forms
from .models import OrderData
from django.urls import reverse_lazy
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column, Field
from django.core.validators import RegexValidator

class OrderDataForm(forms.Form):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_action = reverse_lazy('thankyou')
        self.helper.form_method = 'get'
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-3'
        self.helper.field_class = 'col-lg-3'
        self.helper.layout = Layout(
            'typeOfPlan',
            'firstName',
            'lastName',
            'email',
            'phone',
            'cases',
            'address1',
            'address2',
            'city',
            'state',
            'comments'
        )
        self.helper.add_input(Submit('submit', 'Submit Order'))
        self.helper.attrs['autocomplete'] = 'off'
  
        for field in self.fields.values():
            field.widget.attrs['title'] = ''

    STATES = [
        ('', 'Choose...'),
        ('AL', 'Alabama'),
        ('AK', 'Alaska'),
        ('AZ', 'Arizona'),
        ('AR', 'Arkansas'),
        ('CA', 'California'),
        ('CO', 'Colorado'),
        ('CT', 'Connecticut'),
        ('DE', 'Delaware'),
        ('FL', 'Florida'),
        ('GA', 'Georgia'),
        ('HI', 'Hawaii'),
        ('ID', 'Idaho'),
        ('IL', 'Illinois'),
        ('IN', 'Indiana'),
        ('IA', 'Iowa'),
        ('KS', 'Kansas'),
        ('KY', 'Kentucky'),
        ('LA', 'Louisiana'),
        ('ME', 'Maine'),
        ('MD', 'Maryland'),
        ('MA', 'Massachusetts'),
        ('MI', 'Michigan'),
        ('MN', 'Minnesota'),
        ('MS', 'Mississippi'),
        ('MO', 'Missouri'),
        ('MT', 'Montana'),
        ('NE', 'Nebraska'),
        ('NV', 'Nevada'),
        ('NH', 'New Hampshire'),
        ('NJ', 'New Jersey'),
        ('NM', 'New Mexico'),
        ('NY', 'New York'),
        ('NC', 'North Carolina'),
        ('ND', 'North Dakota'),
        ('OH', 'Ohio'),
        ('OK', 'Oklahoma'),
        ('OR', 'Oregon'),
        ('PA', 'Pennsylvania'),
        ('RI', 'Rhode Island'),
        ('SC', 'South Carolina'),
        ('SD', 'South Dakota'),
        ('TN', 'Tennessee'),
        ('TX', 'Texas'),
        ('UT', 'Utah'),
        ('VT', 'Vermont'),
        ('VA', 'Virginia'),
        ('WA', 'Washington'),
        ('WV', 'West Virginia'),
        ('WI', 'Wisconsin'),
        ('WY', 'Wyoming'),
    ]

    PLANTYPE = [
        ('Basic','Basic Plan'),
        ('Premium','Premium Plan'),
        ('Elite','Elite Plan'),
    ]

    typeOfPlan = forms.TypedChoiceField(
            label = "Type of Plan",
            choices = PLANTYPE,
            required = False,
        )

    firstName = forms.CharField(
        label = "First Name",
        max_length = 200,
        required = False,
    )

    lastName = forms.CharField(
        label = "Last Name",
        max_length = 200,
        required = False,
    )

    email = forms.EmailField(
        label = "Email Address",
        max_length = 200,
        required = False,
    )

    phone_regex = RegexValidator(
        regex=r'^\+?1?\d{9,15}$',
        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed."
    )

    phone = forms.IntegerField(
        validators=[phone_regex],
        label = "Phone",
        required = False,
        widget=forms.TextInput(attrs={'placeholder': '+(515) 555-1212'}),
    )

    cases = forms.IntegerField(
        label = "Number of Cases",
        min_value = 25,
        required = False,
    )

    address1 = forms.CharField(
        label = "Address 1",
        max_length = 200,
        required = False,
    )

    address2 = forms.CharField(
        label = "Address 2",
        max_length = 200,
        required = False,
    )

    city= forms.CharField(
        label = "City",
        max_length = 200,
        required = False,
    )

    state = forms.TypedChoiceField(
        label = "States",
        choices = STATES,
        required = False,
    )

    comments = forms.CharField(
        label = "Comments",
        max_length=200,
        widget=forms.Textarea(attrs={'rows': 4, 'cols': 50})
    )

hafproject/hafapp/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from django.http import HttpResponse, HttpResponseRedirect
from .models import OrderData
from .forms import OrderDataForm
import requests
import datetime

# Create your views here.
def home(request):
    return render(request, 'home.html')

def pricing(request):
    return render(request, 'partials/pricing.html')

def faqs(request):
    return render(request, 'partials/faqs.html')

def about(request):
    return render(request, 'partials/about.html')

def order(request):
 return render(request, 'partials/order.html')

def booksession(request):
    if request.method == 'POST':
            form = OrderDataForm(request.POST)
            if form.is_valid():
                form.field_order = ['firstname', 'lastname', 'email', 'phone', 'cases', 'address1', 'address2', 'city', 'state', 'comments']
                return HttpResponseRedirect('/thankyou')
    else:
            form = OrderDataForm()

    return render(request, 'partials/book_session.html', {'form': form})

def thankyou(request):
    entOrderData = request.GET
    return render(request, 'partials/thankyou.html', {'entOrderData': entOrderData})

# class thankyou(TemplateView):
#     template_name = 'partials/thankyou.html'

#     def post(self, request):
#         form = OrderDataForm(request.POST)
#         entFormData = {}
#         if form.is_valid():
#             entFormData = form.cleaned_data("post")

#         args = {'form': form, "context": entFormData}
#         return render(request, self.template_name, args)

hafproject/hafapp/templates/home.html
{% load django_bootstrap5 %}

{% bootstrap_css %}
{% bootstrap_javascript %}
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>My Web Page</title>
    <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="image" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,400,700">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/jquery.validate.min.js"></script>
    <script>
      $(document).ready(function() {
          var path = window.location.pathname;
          var page = path.split("/").pop();

          var navElements = document.querySelectorAll('.nav-link');

          for (var i = 0; i < navElements.length; i++) {
              var navItem = navElements[i];
              var link = navItem.getAttribute('href');

              if (link.indexOf(page) !== -1) {
                  navItem.classList.add('active');
              } else if (link.indexOf(page) !== 0) {
                  navItem.classList.remove('active');
              }
          }

          $('#id_phone').mask('+1 (000) 000-0000');
          $("#id_email").validate({
            rules: {
              field: {
                required: true,
                email: true
              }
            }
          });
      });
  </script>
  <style>
    .bg-home {
      background-image: url("{% static 'images/main_hero.jpg' %}");
      background-size: cover;
      background-position: center;
      height: 100vh; /* Adjust as needed */
      background-repeat: no-repeat;
      position: relative;
    }
    .bg-image::after {
      content: '';
      position: absolute;
      top: 0;
      right: 0;
      bottom: 0;
      left: 0;
      /* Adjust color and opacity as needed */
      background: rgba(255, 255, 255, 0.3);
    }

    .text-inverted {
      filter: invert(1) grayscale(100%) brightness(200%);
  }


  }
  </style>
 
</head>
<body>
    {% include 'partials/header.html' %}

    <!-- Include your main content here -->
  <main class="px-0" height="250vh">
    {% block content %}
        <div class="px-4 py-5 my-5 text-center bg-home" width="350px" style="background-color: rgba(211, 211, 211, 0.7); /* light grey with 50% transparency */">
          {% load static %}
            <h1 class="display-5 fw-bold text-body-emphasis" style="background: darkcyan; color: white;">At Health and Fitness Constultants,
            </h1>
            <div class="col-lg-6 mx-auto">
              <p class="lead mb-4" style="background: darkcyan;color: white;">we believe that a healthy lifestyle is not a destination, but a journey. Our mission is to guide you on your path to optimal health and wellness.
              </p>
              <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
                <a href="/pricing" id="linkPricing" name="linkPricing" class="btn btn-primary btn-lg px-4 gap-3">Order Now</a>
              </div>
            </div>
          </div>

    {% endblock %}
    
  </main>

    <!-- Include your footer content here -->
    <footer>
        {% include 'partials/footer.html' %}
    </footer>

</body>
</html>

hafproject/hafapp/templates/partials/about.html
{% extends "home.html" %} {% block content %}
<section>
    <div class="position-relative overflow-hidden p-2 m-md-3 text-center bg-light">
      <div class="col-md-12">
        <h1 class="display-4 fw-normal">Our Consultants</h1>
        <p class="lead fw-normal">Our health and fitness consultants are experienced professionals with a passion for wellness. They provide personalized strategies to help clients achieve their health goals. With a deep understanding of fitness trends and nutritional needs, they are committed to promoting healthier lifestyles.</p>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-4">
        <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="var(--bs-secondary-color)"></rect></svg>
        <h2 class="fw-normal">Heading</h2>
        <p>Some representative placeholder content for the three columns of text below the carousel. This is the first column.</p>
        <p><a class="btn btn-secondary" href="#">View details »</a></p>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4">
        <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="var(--bs-secondary-color)"></rect></svg>
        <h2 class="fw-normal">Heading</h2>
        <p>Another exciting bit of representative placeholder content. This time, we've moved on to the second column.</p>
        <p><a class="btn btn-secondary" href="#">View details »</a></p>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4">
        <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="var(--bs-secondary-color)"></rect></svg>
        <h2 class="fw-normal">Heading</h2>
        <p>And lastly this, the third column of representative placeholder content.</p>
        <p><a class="btn btn-secondary" href="#">View details »</a></p>
      </div><!-- /.col-lg-4 -->
    </div>
  {% endblock %}
</section>

hafproject/hafapp/templates/partials/book_session.html
{% extends "home.html" %} {% block content %} {% load crispy_forms_tags %}
<section>
  <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
    <h1 class="display-4 fw-normal">Book a Session</h1>
    <p class="fs-5 text-muted">
      Use this form to book a session with one of our health and fitness consultants. Thank you for your business.
    </p>
  </div>
  <div class="container justify-content-center">
      {% csrf_token %}
      {% crispy form %}
      <script>
        document.getElementById("id_cases").min = 25;
        document.getElementById("id_cases").max = 100;
      </script>
  </div>
</section>
{% endblock %}

hafproject/hafapp/templates/partials/ent_order.html
{% extends "home.html" %} {% block content %} {% load crispy_forms_tags %}
<section>
  <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
    <h1 class="display-4 fw-normal">Enterpise Order Form</h1>
    <p class="fs-5 text-muted">
      Use this form to order more than 25 cases of our product. We will contact you. Thank you for your business.
    </p>
  </div>
  <div class="container justify-content-center">
      {% csrf_token %}
      {% crispy form %}
      <script>
        document.getElementById("id_cases").min = 25;
        document.getElementById("id_cases").max = 100;
      </script>
  </div>
</section>
{% endblock %}

hafproject/hafapp/templates/partials/faqs.html
{% extends "home.html" %} {% block content %}
<section>
  <div class="row g-5">
    <div class="col-md-8">
      <div
        class="position-relative overflow-hidden p-2 m-md-3 text-center bg-light"
      >
        <div class="col-md-12">
          <h1 class="display-4 fw-normal">Frequently Asked Questions</h1>
          <p class="lead fw-normal">
            Welcome to your journey towards a healthier lifestyle! Our expert health and fitness consultants are here to guide you every step of the way. With personalized plans and dedicated support, we’re committed to helping you achieve your wellness goals. Start your transformation with us today
          </p>
        </div>
      </div>

      <article class="blog-post p-5">
        <h2 class="blog-post-title">What services do you offer?</h2>
        <p>
          We offer personalized health and fitness consulting services,
          including workout plans, nutritional guidance, and progress tracking.
        </p>
<hr>
        <h2 class="blog-post-title">What are your pricing plans?</h2>
        <p>
          We offer three pricing plans: Basic at $99/month, Premium at
          $149/month, and Elite at $199/month. Each plan offers different levels
          of service to cater to your specific needs.
        </p>
        <hr>
        <h2 class="blog-post-title">How often will I have check-ins?</h2>
        <p>
          The frequency of check-ins depends on your chosen plan. The Basic Plan
          includes monthly progress tracking, the Premium Plan offers bi-weekly
          check-ins, and the Elite Plan provides weekly one-on-one sessions.
        </p>
        <hr>
        <h2 class="blog-post-title">Can I switch plans?</h2>
        <p>
          Yes, you can upgrade or downgrade your plan at any time. Please
          contact our support team for assistance.
        </p>
        <hr>
        <h2 class="blog-post-title">
          What is included in the nutritional guidance?
        </h2>
        <p>
          Our nutritional guidance includes personalized meal planning based on
          your dietary preferences and fitness goals.
        </p>
        <hr>
        <h2 class="blog-post-title">
          What if I have specific dietary restrictions or allergies?
        </h2>
        <p>
          Our consultants are trained to accommodate specific dietary needs.
          Please inform us of any restrictions or allergies during your initial
          assessment.
        </p>
        <hr>
        <h2 class="blog-post-title">
          Do I need any special equipment for the workout plans?
        </h2>
        <p>
          Most of our workout plans can be done with minimal equipment. If any
          special equipment is needed, it will be clearly stated in the plan.
        </p>
        <hr>
        <h2 class="blog-post-title">
          What if I have a pre-existing medical condition?
        </h2>
        <p>
          Please consult with your healthcare provider before starting any new
          fitness program. We can adjust your plan according to any restrictions
          or recommendations from your healthcare provider.
        </p>
      </article>
    </div>

    <div class="col-md-4">
      <div class="position-sticky" style="top: 2rem">
        <div class="p-4">
          <h4 class="fst-italic">FAQ Archives</h4>
          <ol class="list-unstyled mb-0">
            <li><a href="#">March 2021</a></li>
            <li><a href="#">February 2021</a></li>
            <li><a href="#">January 2021</a></li>
            <li><a href="#">December 2020</a></li>
            <li><a href="#">November 2020</a></li>
            <li><a href="#">October 2020</a></li>
            <li><a href="#">September 2020</a></li>
            <li><a href="#">August 2020</a></li>
            <li><a href="#">July 2020</a></li>
            <li><a href="#">June 2020</a></li>
            <li><a href="#">May 2020</a></li>
            <li><a href="#">April 2020</a></li>
          </ol>
        </div>

        <div class="p-4">
          <h4 class="fst-italic">Other FAQs Resources</h4>
          <ol class="list-unstyled">
            <li><a href="#">GitHub</a></li>
            <li><a href="#">Twitter</a></li>
            <li><a href="#">Facebook</a></li>
          </ol>
        </div>
      </div>
    </div>
  </div>
  {% endblock %}
</section>

hafproject/hafapp/templates/partials/footer.html
<footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><a href="home" class="nav-link" aria-current="page">Home</a></li>
      <li class="nav-item"><a href="booksession" class="nav-link">Book a Session</a></li>
      <li class="nav-item"><a href="pricing" class="nav-link">Session Pricing</a></li>
      <li class="nav-item"><a href="faqs" class="nav-link">FAQs</a></li>
      <li class="nav-item"><a href="about" class="nav-link">About</a></li>
    </ul>
    <p class="text-center text-body-secondary">© 2024 Jeremy Lankford.</p>
  </footer>

hafproject/hafapp/templates/partials/header.html
<header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
  <div class="container">
    <div class="row">
      <div class="col-3">
        <a href="/" class="d-flex align-items-left mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
          {% load static %}
          <img class="d-block mx-auto mb-4" src="{% static 'images/logo.png' %}" alt="" width="250px">
        </a>
      </div>
      <div class="col-9">
          <ul class="nav nav-pills justify-content-end">
            <li class="nav-item"><a href="home" class="nav-link" aria-current="page">Home</a></li>
            <li class="nav-item"><a href="booksession" class="nav-link">Book a Session</a></li>
            <li class="nav-item"><a href="pricing" class="nav-link">Session Pricing</a></li>
            <li class="nav-item"><a href="faqs" class="nav-link">FAQs</a></li>
            <li class="nav-item"><a href="about" class="nav-link">About</a></li>
          </ul>
          <div class="d-flex justify-content-end">
            <a href="#" class="btn btn-primary m-2 rounded-circle" style="width: 33px; height: 30px;">
                <i class="fa fa-facebook"></i>
            </a>
            <a href="#" class="btn btn-info m-2 rounded-circle" style="width: 33px; height: 30px;">
                <i class="fa fa-twitter"></i>
            </a>
            <a href="#" class="btn btn-danger m-2 rounded-circle" style="width: 33px; height: 30px;">
                <i class="fa fa-youtube"></i>
            </a>
            <a href="#" class="btn btn-light m-2 rounded-circle" style="width: 33px; height: 30px;">
                <i class="fa fa-linkedin-in"></i>
            </a>
            <a href="#" class="btn btn-dark m-2 rounded-circle" style="width: 33px; height: 30px;">
                <i class="fa fa-github"></i>
            </a>
        </div>
      </div>
</div>
  </header>

hafproject/hafapp/templates/partials/med_order.html
{% extends "home.html" %} {% block content %} {% load crispy_forms_tags %}
<section>
  <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
    <h1 class="display-4 fw-normal">Medium Business Order Form</h1>
    <p class="fs-5 text-muted">
      Use this form for 13 -25  cases of our product. We will contact you. Thank you for your business.
    </p>
  </div>
  <div class="container justify-content-center">
    {% csrf_token %}
    {% crispy form %}
    <script>
      document.getElementById("id_cases").min = 13;
      document.getElementById("id_cases").max = 25;
    </script>
  </div>
</section>
{% endblock %}

hafproject/hafapp/templates/partials/order.html
{% extends "home.html" %}
{% block content %}
    <section>
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal">Order Form</h1>
            <p class="fs-5 text-muted">Quickly build an effective pricing table for your potential customers with this Bootstrap example. It’s built with default Bootstrap components and utilities with little customization.</p>
        </div>
        <form action="/thankyou" method="post">
        {% csrf_token %}
        <div class="mb-3">
            <h1>{{ form.tier1_value.label_tag }}</h1>
        </div>
        <div class="mb-3">
            <label for="responsibleParty" class="form-label">Responsible Party:</label>
            <input type="text" class="form-control" id="responsibleParty">
        </div>
        <div class="mb-3">
            <label for="deliveryAddress" class="form-label">Delivery Address:</label>
            <input type="text" class="form-control" id="deliveryAddress">
        </div>
        <div class="mb-3 form-check">
        <input type="checkbox" class="form-check-input" id="callVerify">
        <label class="form-check-label" for="callVerify">Call me to verify order</label>
        </div>
        <button type="submit" id="submit_order" class="btn btn-primary">Submit Order</button>
    </form>
    </section>
{% endblock %}

hafproject/hafapp/templates/partials/pricing.html
{% extends "home.html" %}
{% block content %}
<section>
  
    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
        <h1 class="display-4 fw-normal">Session Pricing Plans</h1>
        <p class="fs-5 text-muted">Experience personalized health and fitness guidance tailored to your unique lifestyle and goals. Our expert consultants offer comprehensive plans, from basic to elite, designed to fit your needs and budget. Start your wellness journey with us today and embrace a healthier, happier you!</p>
      </div>
 
      <div class="row row-cols-1 row-cols-md-3 mb-3 text-center m-5">
        <form action="/booksession" method="post">
          {% csrf_token %}
        <div class="col">
          <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
              <h4 class="my-0 fw-normal">Basic Plan</h4>
            </div>
            <div class="card-body">
              <h1 class="card-title pricing-card-title">$99<small class="text-muted fw-light">/month</small></h1>
              <ul class="list-unstyled mt-3 mb-4">
                <li>Initial health and fitness assessment</li>
                <li>Personalized workout plan</li>
                <li>Monthly progress tracking</li>
              </ul>
              <input type="submit" id="booksession" name="booksession" class="w-100 btn btn-lg btn-primary" />
            </div>
          </div>
        </div>
      </form>
      <form action="/med_order" method="post">
        {% csrf_token %}
        <div class="col">
          <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
              <h4 class="my-0 fw-normal">Premium Plan</h4>
            </div>
            <div class="card-body">
              <h1 class="card-title pricing-card-title">$149<small class="text-muted fw-light">/month</small></h1>
              <ul class="list-unstyled mt-3 mb-4">
                <li>All features of the Basic Plan</li>
                <li>Nutritional guidance and meal planning</li>
                <li>Bi-weekly check-ins for progress tracking</li>
              </ul>
              <input type="submit" id="med_order" name="med_order" class="w-100 btn btn-lg btn-primary" />
            </div>
          </div>
        </div>
      </form>
      <form action="/ent_order" method="post">
        {% csrf_token %}
        <div class="col">
          <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
              <h4 class="my-0 fw-normal">Elite Plan</h4>
            </div>
            <div class="card-body">
              <h1 class="card-title pricing-card-title">$249<small class="text-muted fw-light">/month</small></h1>
              <ul class="list-unstyled mt-3 mb-4">
                <li>2All features of the Premium Plan</li>
                <li>Weekly one-on-one virtual sessions</li>
                <li>Priority support and consultation</li>
              </ul>
              <input type="submit" id="ent_order" name="ent_order" class="w-100 btn btn-lg btn-primary" />
            </div>
          </div>
        </div>
      </form>
    </div>
</section>
{% endblock %}

hafproject/hafapp/templates/partials/productinfo.html
{% extends "home.html" %}
{% block content %}
<section>
    <main>
      <div class="position-relative overflow-hidden p-2 m-md-3 text-center bg-light">
        <div class="col-md-12">
          <h1 class="display-4 fw-normal">Our Consultants</h1>
          <p class="lead fw-normal">Our health and fitness consultants are experienced professionals with a passion for wellness. They provide personalized strategies to help clients achieve their health goals. With a deep understanding of fitness trends and nutritional needs, they are committed to promoting healthier lifestyles.</p>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-4">
          <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="var(--bs-secondary-color)"></rect></svg>
          <h2 class="fw-normal">Heading</h2>
          <p>Some representative placeholder content for the three columns of text below the carousel. This is the first column.</p>
          <p><a class="btn btn-secondary" href="#">View details »</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="var(--bs-secondary-color)"></rect></svg>
          <h2 class="fw-normal">Heading</h2>
          <p>Another exciting bit of representative placeholder content. This time, we've moved on to the second column.</p>
          <p><a class="btn btn-secondary" href="#">View details »</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="var(--bs-secondary-color)"></rect></svg>
          <h2 class="fw-normal">Heading</h2>
          <p>And lastly this, the third column of representative placeholder content.</p>
          <p><a class="btn btn-secondary" href="#">View details »</a></p>
        </div><!-- /.col-lg-4 -->
      </div>
      </main>
{% endblock %}
</section>